//Users
export const ADD_USER = "ADD_USER"
export const ADD_USER_SESSION = "ADD_USER_SESSION"
export const CHECK_NONCE = "CHECK_NONCE"
export const GENERATE_NONCE = "GENERATE_NONCE"
export const SEND_NONCE = "SEND_NONCE"
//KDC
export const ADD_KDC_USER = "ADD_KDC_USER"
export const ADD_KDC_SESSION = "ADD_KDC_SESSION"
export const ADD_KDC_SESSION_USER = "ADD_KDC_SESSION_USER"
export const SEND_KDC_SESSION = "SEND_KDC_SESSION"
//Queues
export const PRODUCE_SESSION_REQUEST = "PRODUCE_SESSION_REQUEST"
export const CONSUME_SESSION_REQUEST = "CONSUME_SESSION_REQUEST"